# Generated by Django 5.0.6 on 2024-07-11 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField()),
                ('contact_number', models.CharField(max_length=15)),
                ('gender_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('user_role', models.CharField(max_length=120)),
                ('user_country', models.CharField(max_length=180)),
                ('user_address', models.CharField(max_length=750)),
                ('languages', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=40)),
                ('user_balance', models.IntegerField(default=0)),
                ('user_description', models.TextField()),
                ('account_type', models.CharField(choices=[('Freelancer', 'Freelancer'), ('Client', 'Client')], max_length=70, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField()),
                ('profile_title', models.CharField(max_length=350)),
                ('profole_category', models.CharField(max_length=230)),
                ('contact_number', models.CharField(max_length=15)),
                ('gender_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('user_role', models.CharField(max_length=120)),
                ('user_country', models.CharField(max_length=180)),
                ('user_address', models.CharField(max_length=750)),
                ('languages', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=40)),
                ('user_education', models.TextField()),
                ('user_balance', models.IntegerField(default=0)),
                ('user_description', models.TextField()),
                ('account_type', models.CharField(choices=[('Freelancer', 'Freelancer'), ('Client', 'Client')], max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_account', to=settings.AUTH_USER_MODEL)),
                ('user_skill', models.ManyToManyField(to='skills.skills')),
            ],
        ),
    ]
