# Generated by Django 5.0.6 on 2024-07-08 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_image', models.URLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField()),
                ('contact_number', models.CharField(max_length=15)),
                ('gender_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('user_role', models.CharField(max_length=120)),
                ('user_country', models.CharField(max_length=180)),
                ('user_address', models.CharField(max_length=750)),
                ('languages', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=40)),
                ('user_balance', models.IntegerField(default=0)),
                ('user_description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='account.category')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField()),
                ('profile_title', models.CharField(max_length=350)),
                ('profole_category', models.CharField(max_length=230)),
                ('contact_number', models.CharField(max_length=15)),
                ('gender_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('user_role', models.CharField(max_length=120)),
                ('user_country', models.CharField(max_length=180)),
                ('user_address', models.CharField(max_length=750)),
                ('languages', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=40)),
                ('user_education', models.TextField()),
                ('user_balance', models.IntegerField(default=0)),
                ('user_description', models.TextField()),
                ('account_type', models.CharField(choices=[('Frelancer', 'Frelancer'), ('Client', 'Client')], max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_account', to=settings.AUTH_USER_MODEL)),
                ('user_skill', models.ManyToManyField(to='account.skills')),
            ],
        ),
    ]
