# Generated by Django 5.0.6 on 2024-07-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerprofile',
            old_name='profole_category',
            new_name='profile_category',
        ),
    ]
