# Generated by Django 5.0.6 on 2024-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_category_category_image'),
        ('post', '0002_alter_post_post_category_alter_post_required_skill'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='category',
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='account_type',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('Client', 'Client')], max_length=70),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='user_skill',
            field=models.ManyToManyField(to='skills.skills'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
