# Generated by Django 5.0.6 on 2024-07-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='proposal_ammount',
            new_name='proposal_amount',
        ),
    ]
